global using Microsoft.AspNetCore.Mvc;
global using api.Settings;
global using Microsoft.Extensions.Options;
global using MongoDB.Driver;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using api.Interfaces;
global using api.Models;
global using api.DTOs;